[package]
name = "{{package_name}}-yew"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
js-sys = "0.3.59"
serde = "1.0.140"
wasm-bindgen = "0.2.82"
wasm-bindgen-futures = "0.4.32"
web-sys = "0.3.59"
yew = "0.19"
