[package]
name = "create-tauri-app"
description = "Rapidly scaffold out a new tauri app project."
authors = [ "Tauri Programme within The Commons Conservancy" ]
version = "3.7.3"
edition = "2021"
license = "Apache-2.0 OR MIT"
readme = "README.md"
repository = "https://github.com/tauri-apps/create-tauri-app"
keywords = [ "tauri" ]
categories = [ "gui" ]
exclude = [ "/node" ]
rust-version = "1.59"

[[bin]]
name = "cargo-create-tauri-app"
path = "src/main.rs"

[dependencies]
anyhow = "1"
dialoguer = "0.10"
pico-args = "0.5"
rust-embed = { version = "6.8", features = [ "compression", "interpolate-folder-path" ] }
