# Copyright 2019-2021 Tauri Programme within The Commons Conservancy
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT

name: version or publish

on:
  push:
    branches:
      - rewrite-in-rust # TODO: adjust before merging for stable 2.0

jobs:
  version-or-publish:
    runs-on: ubuntu-latest
    timeout-minutes: 65
    outputs:
      change: ${{ steps.covector.outputs.change }}
      commandRan: ${{ steps.covector.outputs.commandRan }}
      successfulPublish: ${{ steps.covector.outputs.successfulPublish }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          check-latest: true
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'
          cache-dependency-path: 'node/pnpm-lock.yaml'

      - name: cargo login
        run: cargo login ${{ secrets.CRATE_TOKEN  }}
      - name: git config
        run: |
          git config --global user.name "${{ github.event.pusher.name }}"
          git config --global user.email "${{ github.event.pusher.email }}"

      - name: covector version or publish (publish when no change files present)
        uses: jbolda/covector/packages/action@covector-v0
        id: covector
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          command: 'version-or-publish'
          createRelease: true
          draftRelease: true

      - name: Create Pull Request With Versions Bumped
        if: steps.covector.outputs.commandRan == 'version'
        uses: tauri-apps/create-pull-request@v3.4.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: release/version-updates-alpha # TODO: adjust before merging for stable 2.0
          title: Apply Version Updates From Current Changes (Alpha) # TODO: adjust before merging for stable 2.0
          commit-message: 'apply version updates (alpha)' # TODO: adjust before merging for stable 2.0
          labels: 'version updates'
          body: ${{ steps.covector.outputs.change }}

      - name: Trigger publish-binaries.yml workflow
        if: |
          steps.covector.outputs.successfulPublish == 'true' &&
          contains(steps.covector.outputs.packagesPublished, 'create-tauri-app')
        uses: benc-uk/workflow-dispatch@v1 # TODO: adjust before merging for stable 2.0 maybe use repository dispatch???
        with:
          workflow: publish binaries
          repo: tauri-apps/create-tauri-app
          inputs: '{"releaseId": "${{ steps.covector.outputs.releaseId }}" }'
          token: ${{ secrets.TAURI_BOT_PAT }}

      - name: Trigger publish-napi.yml workflow
        if: |
          steps.covector.outputs.successfulPublish == 'true' &&
          contains(steps.covector.outputs.packagesPublished, 'create-tauri-app-js')
        uses: benc-uk/workflow-dispatch@v1 # TODO: adjust before merging for stable 2.0 maybe use repository dispatch???
        with:
          workflow: publish napi modules
          repo: tauri-apps/create-tauri-app
          token: ${{ secrets.TAURI_BOT_PAT }}
